Switching back to osmdroid-itinerennes:1.0.1 fixes app start issue
With the latest osmdroid-android library we are issuing a VerifyError.
Using the old osmdroid-itinerennes:1.0.1 instead of osmdroid-android:4.0.0
or osmdroid-itinerennes:1.1 solved the issue.

But there still is an issue with the new itinerennes-java-api:1.0 :
```
java.lang.RuntimeException: An error occured while executing doInBackground()
...
Caused by: java.lang.VerifyError: fr.itinerennes.api.client.ApiHttpResponseHandler
  at fr.itinerennes.api.client.JsonItineRennesApiClient.getStop(JsonItineRennesApiClient.java:122)
...
```